# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82f4cbdc74e067f72730b4c8ee5fb1409980ec2aa9d7018ce7b640629ff14a83443849fb009225784fde12f0552487986394c2f3beb99bc4763f073647b555f1

test:
  secret_key_base: 886bde44ca4171406bf17e25600ce97e62f073f9128eb75f006cd92015e9334ecf47ee101fa98ef2fb816e04854e5da291e5fc9e2b07e197cb74d16026af0977
  
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 2eb8ceeaf09042a4edda0c6dc8d8b564674f76bed3780bd220b4bd208e123823bc2b5254c40b0be9278029694b389e569ee17f1516a349a545663be7a6331e2b
  slack_url: <%= ENV["SLACK_WEBHOOK_URL"] %>